sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: O80/s6sGTn6M94IuFgmYbm7SSqXIxZ0KlTuGW4kKNKxxBoWCSPbMG8Jblw8+Caags9QgpvwVHrjhb7C3MMt/DFrnOeowEa8d/s6l2VkLGt5LJ5u7i5LYjP3i9O24NROjF4hQ1SHhFGn/X9X/lv7/PJy7J/far7wNYppsSkp+mgbhdP6FQtmQ/XDxMluR5EC5IUNS26Y/GOaAzyi9CGv24xeHKX61C9csJks1f9tLWpG32Khk9tbpLUpg4hzNzHYsEDejnK7ljeaWxyGYVcbV9TkfVHOjbZbsYy1X4XiaiML96IG+apqXNAgShFaNmNQ2uhPSaKA2wWIJ0PZidTa43HC77cQXd7+WTukmpB8dZkoOdEbw3U3UZGagHbxG+H9ulvqlmGYCeStlAg+sJu2gwdL+uo+rDn+w7LNWiB31XW3FNAf3NIt7ciSWyiAzt5gNz+GsGmXdDyRbTnTuSf/viFoLr73Bg4h8qV2Kvzj1z6+ADhSOt8oBVrKR8zUsURy5g8QukhY9k2YkYGgRGwFGK306gYrw7jqsn6j6dE/J83rQjDLMkEYWzLnDPw9EgyVu4okQx/coyx8esd1LMhQniuJxBQ7tXagc74r7CzPwKfUI/iiyPZQ3t+VntXnFOvhy4kkt3mqllDeJ+1R92xtHF3Hhr46vjme1h2bG5TjX9Kk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Dark-Hollow_5121
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy